# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  .settings:
    cacophony:
      providers:
        vimeo:
          consumer_key: YOUR_KEY
          consumer_secret: YOUR_SECRET
        twitter:
          consumer_key: YOUR_ANOTHER_KEY
          consumer_secret: YOUR_ANOTHER_SECRET
        facebook:
          consumer_key: YOUR_APP_ID
          consumer_secret: YOUR_APP_SECRET
          scope: user_about_me,user_checkins,user_likes,user_status
        netflix:
          consumer_key: YOUR_NETFLIX_KEY
          consumer_secret: YOUR_NETFLIX_SECRET