<?php

/**
 * TokenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TokenTable extends PluginTokenTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TokenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Token');
    }
}